;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-cut-region
        cua-paste
        indent-for-tab-command
        kill-and-join-forward
        tcl-electric-hash
        ))

(setq mc/cmds-to-run-once
      '(
        ))
