;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        copy-line
        cua-cut-region
        cua-paste
        fill-paragraph
        indent-for-tab-command
        kill-and-join-forward
        ))

(setq mc/cmds-to-run-once
      '(
        ))
