;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-delete-forward
        cua-clear-rectangle-mark
        cua-copy-region
        cua-cut-region
        cua-insert-char-rectangle
        cua-paste
        eval-and-replace
        fill-paragraph
        indent-for-tab-command
        kill-and-join-forward
        kmacro-end-and-call-macro
        perl-indent-command
        tcl-electric-hash
        tcl-indent-command
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        cua-set-rectangle-mark
        mouse-buffer-menu
        write-file
        ))
